// Code generated by "stringer -type=Command"; DO NOT EDIT

package main

import "fmt"

const _Command_name = "NothingUpDownRightLeftBoostNewPlayer"

var _Command_index = [...]uint8{0, 7, 9, 13, 18, 22, 27, 36}

func (i Command) String() string {
	if i < 0 || i >= Command(len(_Command_index)-1) {
		return fmt.Sprintf("Command(%d)", i)
	}
	return _Command_name[_Command_index[i]:_Command_index[i+1]]
}
